export const // ETAT_PREPARATION = 1,
      ETAT_PRET = 2,
      ETAT_UPLOADING = 3,
      ETAT_COMPLETE = 4,
      ETAT_ECHEC = 5,
      ETAT_CONFIRME = 6,
      ETAT_UPLOAD_INCOMPLET = 7,
      ETAT_DOWNLOAD_ENCOURS = 8,
      ETAT_DOWNLOAD_SUCCES_CHIFFRE = 9,
      ETAT_DOWNLOAD_SUCCES_DECHIFFRE = 10,
      LIMITE_DOWNLOAD_SPLIT = 1024 * 1024 * 100,

      CACHE_DOWNLOAD_CHIFFRE = 'fichiersDownloadChiffres',
      CACHE_DOWNLOAD_DECHIFFRE = 'fichiersDownloadDechiffres'
